[build]
  command = "npm run build"
  publish = "dist"

[dev]
  targetPort = 3000

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions/"
  included_files = ["!**/*.test.js"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
